function ASleep = importfile_humanSleepScores(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   ASLEEP = IMPORTFILE(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   ASLEEP = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   ASleep = importfile('7A_Sleep.csv', 3, 11);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/04/29 17:18:01

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Format for each line of text:
%   column1: datetimes (%{MM/dd/yyyy hh:mm:ss a}D)
%	column2: datetimes (%{MM/dd/yyyy hh:mm:ss a}D)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: categorical (%C)
%   column7: double (%f)
%	column8: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{MM/dd/yyyy hh:mm:ss a}D%{MM/dd/yyyy hh:mm:ss a}D%f%f%f%C%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
ASleep = table(dataArray{1:end-1}, 'VariableNames', {'StartTime','EndTime','SleepStartDP','SleepEndDP','Duration','RodentSleep','StartTime1','EndTime1'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% ASleep.StartTime=datenum(ASleep.StartTime);
% ASleep.EndTime=datenum(ASleep.EndTime);

